### ISSUE TITLE
PHP Fatal error:  Uncaught Error: Call to undefined method React\EventLoop\StreamSelectLoop::nextTick()

### ISSUE THREAD

**Issue by kongoon** [binsoul/net-mqtt-client-react#13]
PHP Fatal error:  Uncaught Error: Call to undefined method React\EventLoop\StreamSelectLoop::nextTick() in /vendor/binsoul/net-mqtt-client-react/src/ReactMqttClient.php:656

**Comment by binsoul** [comment]
I released version 0.4.0 which fixes this bug.
