### ISSUE TITLE
Supports username and password authentication and Connection SSL/TLS

### ISSUE THREAD

**Issue by sergioxdev** [binsoul/net-mqtt-client-react#20]
Hi Guys
among the many searches I saw your project, it is very interesting, I wanted to know if it was possible to use:
- Supports username and password authentication 
- SSL/TLS

**Comment by binsoul** [comment]
You can use both. The Connection class has a username and a password property which will be used to establish a connection to the MQTT server. React provides a SecureConnector class which takes care of TLS/encryption.

**Comment by sergioxdev** [comment]
Here is a complete example, for those who need it:

                // Setup client
		$loop = EventLoopFactory::create();
		$dnsResolverFactory = new DNSResolverFactory();
		$connector = new DnsConnector(new TcpConnector($loop), $dnsResolverFactory->createCached($dns, $loop));

		$secureConnector = new SecureConnector($connector, $loop, array('crypto_method' => STREAM_CRYPTO_METHOD_TLSv1_2_CLIENT));



		$client = new ReactMqttClient($secureConnector, $loop);

		$connection_ = new DefaultConnection($username_, $password_, null, $clientid_, 0);
		.
		.
		.
		$client->connect($address, $port, $connection_)->then(
		    function () use ($client) {
		.
		.
		.
			}
		);

		$loop->run();
