### ISSUE TITLE
react/socket-client is deprecated!

### ISSUE THREAD

**Issue by aedart** [binsoul/net-mqtt-client-react#7]
Hi mate,

Could you please switch to using "reactphp/socket"? The `react/socket-client` has been deprecated.

**Comment by aedart** [comment]
Also, it appears that React broke a few things. Getting an `Fatal error:  Call to undefined method React\SocketClient\SecureConnector::create()`

**Comment by aedart** [comment]
Mate... are you still there? Any chance that you have time for this issue?

**Comment by binsoul** [comment]
I'm sorry I was really busy.

You are right. React broke many things used by this library. Removed events, properties are private now, classes are declared final. Oh my...

The "full-drain" event was used to assure that an outgoing message was completely sent before the next one was written to the buffer. This event was removed so incoming data now triggers sending queued outgoing messages. This might be a bit slower but works for me.  Please let me know if you encounter any errors.

**Comment by aedart** [comment]
Hi again - it's good to hear from you.

I'll test the changes you made asap.

**Comment by aedart** [comment]
It appears that your changes work great, when using React's @Connector@.

However, I am unable to use @\React\Socket\SecureConnector@, when connecting to **iot.eclipse.org**. Works fine when using a local mqtt broker!?

**Details**
Whenever I try to use a secure connection, I get an error, in which the @stream@ is attempted closed, yet it is @null@ (An exception is never rejected correctly).

```php

// In the "connect" method.
$this->registerClient($connection, $timeout)
    ->then(function (Connection $connection) use ($deferred) {
        $this->isConnecting = false;
        $this->isConnected = true;
        $this->connection = $connection;

        $this->emit('connect', [$connection, $this]);
        $deferred->resolve($this->connection);
    })
    ->otherwise(function (\Exception $e) use ($deferred, $connection) {
        $this->isConnecting = false;

        $this->emitError($e);
        $deferred->reject($e);

        $this->stream->close(); // Something fails here... when stream is null
        $this->emit('close', [$connection, $this]);
    });
```

Other than this, I have not found any issue - ty for your effort :)

**Comment by binsoul** [comment]
The stream is set to null if a "close" event is emitted. Looks like this is what happens in your case. The close method is now only called if the stream is not null.

There are now two ways to create a connector in react/socket. The long way is:

``` php
$connector = new \React\Socket\SecureConnector(
    new \React\Socket\DnsConnector(
        new \React\Socket\TcpConnector($loop),
        $dnsResolverFactory->create('8.8.8.8', $loop)
    ),
    $loop
);
$client = new ReactMqttClient($connector, $loop);

$client->connect('iot.eclipse.org', 8883)->then(
    function () {
...
```

And the shorter way is:

``` php
$connector = new \React\Socket\Connector($this->loop, ['timeout' => false]);
$client = new ReactMqttClient($connector, $loop);

$client->connect('tls://iot.eclipse.org', 8883)->then(
    function () {
...
```
The second one doesn't work without the "tls://" prefix. It is also used in the unit tests.

I had some strange effects after updating to the current react/socket version. DNS lookups failed and connections couldn't be established. But in my case everything was ok after updating PHP. I also had to delete the react/socket-client package from my vendors folder. The new package loaded classes from the old one if present. Which didn't work too well.

**Comment by aedart** [comment]
So in short, you have updated to PHP 7+?
If that is the case, then that will give me a valid reason to argue for moving forward with PHP upgrades, at my job.

And yea, react has lately been causing me some major issues in regards to backwards compatibility. Wish that Clue (react author) would start using Semantic Versioning 100% and not just break things that careless.

Once again, thanks a lot for all of your efforts :)
